### ISSUE TITLE
Corporate Wallet UI Fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1649]
To be broken into smaller issues:

Functional

1. Corporate Wallet Setup - missing field validations - if I don’t input information in the mandatory fields nothing happens 

UI

- [x] 1. Corporate Wallet Setup - please change the tittle to Wallet instead of Vault
- [x] 2. Corporate Wallet Setup - Continue button should be left aligned with the box above
- [x] 3. Corporate Wallet Setup - please follow the spacing from Invision, paddings inside the box, and vertical spacing of elements
- [x] 4. Date picker - months names should be centered  https://gyazo.com/8848a58a617d05ad8c5560ed1c6334a9 
- [x] 5. Corporate wallet Dashboard  - please change the tittle to Wallet instead of Vault
- [x] 6. Corporate wallet Dashboard - fix vertical spacing of tabs and spacing between boxes
- [x] 7. Corporate wallet Dashboard - Company, application status, cap table, and the rest of the boxes - make sure the elements don’t overflow the box padding https://gyazo.com/f9e7f9a43ba35940ed715c9a8435a4db  & https://gyazo.com/20734b6353b14fa4b9673ef13c414f94
- [ ] 8. Corporate wallet Dashboard - tooltip for chart should have same styling as the one used in the main wallet dashboard for crypto 
- [ ] 9. Corporate wallet Dashboard - structure has ugly white borders because of overflow. https://gyazo.com/1d79ef42882d59bc0ce78acd927b3c73 - should use our own scroll instead
- [x] 10. Informations & Documents - please use the right icon from invision https://gyazo.com/975b88d26dbfaa59287a9f6579c1e36a

**Comment by designhorf** [comment]
@oanamangiurea I'd like to create 2 tickets from this one. 
- one for the Functional (missing field validations) issue, and 
- another one for the Shareholder Chart tooltip style. 

I couldn't reproduce the number 9th issue. Or maybe it was fixed earlier. 
https://gyazo.com/1d79ef42882d59bc0ce78acd927b3c73

**Comment by CortecKYC** [comment]
@rhdelima please QA

**Comment by rhdelima** [comment]
Looks good. Pass

**Comment by oanamangiurea** [comment]
@designhorf 

Issue 9 still reproduces on Mac https://gyazo.com/89c577f480bda7f24610341b7a8cdf42 
Issue 4 still reproduces https://gyazo.com/c8fe71471b19f078fe4c5fbf3bf6ef75

**Comment by designhorf** [comment]
@oanamangiurea 
Issue 4 - I've just checked `dev` branch and got this result -> 
<img width="339" alt="Screenshot 2019-10-08 at 15 00 11" src="https://user-images.githubusercontent.com/7461010/66397664-93027700-e9dc-11e9-8f6e-d725db3d0c63.png">
@rhdelima can you have a look at this issue please?

**Comment by designhorf** [comment]
@rhdelima Issue 4 is not actual, found a solution, fix is on its way

**Comment by rhdelima** [comment]
Waiting for the merge however I can't replicate 4 and 9 on the latest build.

![image](https://user-images.githubusercontent.com/10294014/66535741-2955aa80-eb4d-11e9-9b98-ac5550a3c778.png)

![image](https://user-images.githubusercontent.com/10294014/66535765-3f636b00-eb4d-11e9-98e2-6eecdc749625.png)

**Comment by CortecKYC** [comment]
@rhdelima Why is this ticket blocked for QA?

**Comment by rhdelima** [comment]
@CortecKYC `Structure` section is currently hidden which where issue 9 was found.

**Comment by CortecKYC** [comment]
Okay, @rhdelima When you block a ticket, please state the reason in a comment so we can keep track later.

**Comment by CortecKYC** [comment]
@rhdelima Is this ticket still blocked?

**Comment by rhdelima** [comment]
@CortecKYC Yes. `Structure` is not yet added back on corp dashboard

**Comment by sk91** [comment]
@rhdelima @CortecKYC Structure is irrelevant right now, because we are not planning to add it back soon

**Comment by CortecKYC** [comment]
Then let's close it.
